SistemaMVC1/SistemaLojaMvcApi1/Controllers/OrdensController.cs
using SistemaLojaMvcApi1.Models;
using SistemaLojaMvcApi1.ViewsModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaLojaMvcApi1.Controllers
{

    public class OrdensController : Controller
    {
        private SistemaLojaMvcApi1Context db = new SistemaLojaMvcApi1Context();

        // GET: Ordens
        public ActionResult NovaOrdem()
        {
            var ordemView = new OrdemView();
            ordemView.Customizar = new Customizar();
            ordemView.Produtos = new List<ProdutoOrdem>();
            Session["ordemView"] = ordemView;
            
            var lista = db.Customizars.ToList();
            //Campo para inicar no formulario a opção Selecione....
            //lista.Add(new TipoDocumento { TipoDocumentoId = 0, Descricao = "[Selecione...]" });
            lista = lista.OrderBy(c => c.NomeCompleto).ToList();
            ViewBag.CustomizarId = new SelectList(lista, "CustomizarId", "NomeCompleto");

            return View(ordemView);
        }

        [HttpPost]
        public ActionResult NovaOrdem(OrdemView ordemView)
        {
            ordemView = Session["ordemView"] as OrdemView;
            var customizarId = int.Parse(Request["CustomizarId"]);
            
            if (customizarId == 0)
            {
                var lista = db.Customizars.ToList();
                lista.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione...]" });
                lista = lista.OrderBy(c => c.NomeCompleto).ToList();
                ViewBag.CustomizarId = new SelectList(lista, "CustomizarId", "NomeCompleto");

                //Tratamento de erro
                ViewBag.Error = "Selecione um Cliente.";

                return View(ordemView);
            }

            var cliente = db.Produtoes.Find(customizarId);

            if (cliente == null)
            {
                var lista = db.Customizars.ToList();
                lista.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione...]" });
                lista = lista.OrderBy(c => c.NomeCompleto).ToList();
                ViewBag.CustomizarId = new SelectList(lista, "CustomizarId", "NomeCompleto");

                //Tratamento de erro
                ViewBag.Error = "O cliente não existe.";

                return View(ordemView);
            }

            if(ordemView.Produtos.Count == 0)
            {
                var lista = db.Customizars.ToList();
                lista.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione...]" });
                lista = lista.OrderBy(c => c.NomeCompleto).ToList();
                ViewBag.CustomizarId = new SelectList(lista, "CustomizarId", "NomeCompleto");

                return View(ordemView);
            }

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    //Salvando uma ordem
                    var ordem = new Ordem
                    {
                        CustomizarId = customizarId,
                        OrdemData = DateTime.Now,
                        OrdemStatus = OrdemStatus.Criada
                    };

                    db.Ordem.Add(ordem);
                    db.SaveChanges();
                    
                    //Salvando ordem detalhes
                    var ordemId = db.Ordem.ToList().Select(o => o.OrdemId).Max();

                    foreach (var item in ordemView.Produtos)
                    {
                        var ordemDetalhes = new OrdemDetalhe
                        {
                            ProdutoId = item.ProdutoId,
                            OrdemId = ordemId,
                            Descricao = item.Descricao,
                            Preco = item.Preco,
                            Quantidade = item.Quantidade
                        };

                        db.OrdemDetalhe.Add(ordemDetalhes);
                        db.SaveChanges();
                    }

                    //Commit para acetiar a transação
                    transaction.Commit();
                    ViewBag.Sucesso = string.Format("Ordem: {0}, foi salva com sucesso.", ordemId);
                }
                catch (Exception ex)
                {

                    transaction.Rollback();
                    ViewBag.Erro = "Erro " + ex.ToString();
                }
            }


            

            var lista2 = db.Customizars.ToList();
            lista2.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione...]" });
            lista2 = lista2.OrderBy(c => c.NomeCompleto).ToList();
            ViewBag.CustomizarId = new SelectList(lista2, "CustomizarId", "NomeCompleto");

            ordemView = new OrdemView();
            ordemView.Customizar = new Customizar();
            ordemView.Produtos = new List<ProdutoOrdem>();
            Session["ordemView"] = ordemView;

            return View();
        }

        public ActionResult AddProduto()
        {
            var lista = db.Produtoes.ToList();
            //Campo para inicar no formulario a opção Selecione....
            lista.Add(new ProdutoOrdem { ProdutoId = 0, Descricao = "[Selecione...]" });
            lista = lista.OrderBy(c => c.Descricao).ToList();
            ViewBag.ProdutoId = new SelectList(lista, "ProdutoId", "Descricao");

            return View();
        }

        [HttpPost]
        public ActionResult AddProduto(ProdutoOrdem produtoOrdem)
        {
            var ordemView = Session["ordemView"] as OrdemView;

            var produtoId = int.Parse(Request["ProdutoId"]);

            if(produtoId == 0)
            {
                var lista = db.Produtoes.ToList();
                lista.Add(new ProdutoOrdem { ProdutoId = 0, Descricao = "[Selecione...]" });
                lista = lista.OrderBy(c => c.Descricao).ToList();
                ViewBag.ProdutoId = new SelectList(lista, "ProdutoId", "Descricao");

                //Tratamento de erro
                ViewBag.Error = "Selecione um Produto.";

                return View(produtoOrdem);
            }

            var produto = db.Produtoes.Find(produtoId);

            if (produto == null)
            {
                var lista = db.Produtoes.ToList();
                lista.Add(new ProdutoOrdem { ProdutoId = 0, Descricao = "[Selecione...]" });
                lista = lista.OrderBy(c => c.Descricao).ToList();
                ViewBag.ProdutoId = new SelectList(lista, "ProdutoId", "Descricao");

                //Tratamento de erro
                ViewBag.Error = "Não existe um produto selecionado.";

                return View(produtoOrdem);
            }

            //ID do produto já adicionado, só altera a quantidade não adiciona um novo produto
            produtoOrdem = ordemView.Produtos.Find(p => p.ProdutoId == produtoId);
            if (produtoOrdem == null)
            {
                produtoOrdem = new ProdutoOrdem
                {
                    Descricao = produto.Descricao,
                    Preco = produto.Preco,
                    ProdutoId = produto.ProdutoId,
                    Quantidade = float.Parse(Request["Quantidade"])
                };

                ordemView.Produtos.Add(produtoOrdem);
            }
            else
            {
                produtoOrdem.Quantidade += float.Parse(Request["Quantidade"]);
            }


            var listac = db.Customizars.ToList();
            //Campo para inicar no formulario a opção Selecione....
            //listac.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione um cliente...]" });
            listac = listac.OrderBy(c => c.NomeCompleto).ToList();
            ViewBag.CustomizarId = new SelectList(listac, "CustomizarId", "NomeCompleto");

            return View("NovaOrdem", ordemView);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaMVC1/SistemaLojaMvcApi1/Views/Ordens/AddProduto.cshtml
@model SistemaLojaMvcApi1.Models.ProdutoOrdem

@{
    ViewBag.Title = "Adicionar Produto";
}

<h2>Adicionar Produto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoId, "Produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProdutoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <input type="submit" value="Adicionar" id="NovaOrdem" class="btn btn-success" />

        <footer>
            <h4 class="text-danger">
                @ViewBag.Error
            </h4>
        </footer>
    </div>
}

SistemaMVC1/SistemaLojaMvcApi1/Views/Ordens/NovaOrdem.cshtml
@model SistemaLojaMvcApi1.ViewsModels.OrdemView

@{
    ViewBag.Title = "Nova Ordem";
}

<h3>Detalhes do Pedido</h3>

@using (Html.BeginForm("NovaOrdem", "Ordens", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.Customizar.CustomizarId, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CustomizarId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Customizar.CustomizarId, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ActionLink("Adicionar Produto", "AddProduto", new { }, new { @class = "btn btn-primary" }) |

    <input type="submit" value="Criar Ordem" id="NovaOrdem" class="btn btn-success" />

</div>
}

<h4>Detalhes do Pedido</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Quantidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Valor)
        </th>
        <th></th>
    </tr>

    @for (int i = 0; i < Model.Produtos.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Quantidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Valor)
            </td>
            
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = Model.Produtos[i].ProdutoId }) |
                @Html.ActionLink("Excluir", "Delete", new { id = Model.Produtos[i].ProdutoId })
            </td>
        </tr>
    }

</table>

<footer>
    <h4 class="text-danger alert-danger alert-dismissable">
        @ViewBag.Error
    </h4>
    <h4 class="text-success alert-success">
        @ViewBag.Sucesso
    </h4>
</footer>